<a href="https://colab.research.google.com/github/mohammad-nahid-hossain/MSc.-Projects/blob/main/My_CI_Project_DT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
!ls "/content/drive/My Drive/"

 2014_Bodily_Maps_of_Emotions.mat
'2019110211_Hossain Mohammad Nahid.gdoc'
 Books
'Books(islamic)'
'Bsc Thesis'
 CERTIFICATES
'Colab Notebooks'
 Coursera
 CV
'Data Acquisition for research work'
 DeepLearningBook.pdf
'Dream forest tour'
'Getting started.pdf'
'GME transaction'
 Hmmmmm.gsheet
'How to install cuda 10.1 in Ubuntu 18.04.zip'
 IMG_4717.JPG
 IMG_4719.JPG
 lecture_1.pdf
 lecture_2.pdf
 lecture_3.pdf
 lecture_4.pdf
 Msc
 Neural-Network-based-finger-counting-technique.pdf
'New Doc 2019-09-03 20.05.57.jpg'
 Paper
'PhD Application'
'PhD Application Pack'
'Planning Document.docx'
'Planning Document.odt'
'Planning Document.pdf'


In [ ]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [ ]:
# Function importing Dataset 
def importdata():
    CI_data = pd.read_csv('/content/drive/My Drive/Msc/Msc Thesis/Coding Documents/WFS/DT/My_Project_CI_data.csv') 
    # Printing the dataswet shape 
    print ("Dataset Length: ", len(CI_data)) 
    print ("Dataset Shape: ", CI_data.shape) 
    
    # Printing the dataset obseravtions 
    print ("Dataset: ",CI_data.head())
    return CI_data 

In [ ]:
# Function to split the dataset 
def splitdataset(CI_data): 
  
    # Separating the target variable 
    X = CI_data.values[:, 0:7] 
    Y = CI_data.values[:, 7] 
  
    # Splitting the dataset into train and test 
    X_train, X_test, y_train, y_test = train_test_split(  
    X, Y, test_size = 0.3, random_state = 100) 
      
    return X, Y, X_train, X_test, y_train, y_test 

In [ ]:
# Function to perform training with giniIndex. 
def train_using_gini(X_train, X_test, y_train): 
  
    # Creating the classifier object 
    clf_gini = DecisionTreeClassifier(criterion = "gini", 
            random_state = 100,max_depth=7, min_samples_leaf=1) 
  
    # Performing training 
    clf_gini.fit(X_train, y_train) 
    return clf_gini

In [ ]:
# Function to perform training with entropy. 
def tarin_using_entropy(X_train, X_test, y_train): 
  
    # Decision tree with entropy 
    clf_entropy = DecisionTreeClassifier( 
            criterion = "entropy", random_state = 100, 
            max_depth = 7, min_samples_leaf = 1) 
  
    # Performing training 
    clf_entropy.fit(X_train, y_train) 
    return clf_entropy 

In [ ]:
# Function to make predictions 
def prediction(X_test, clf_object): 
  
    # Predicton on test with giniIndex 
    y_pred = clf_object.predict(X_test) 
    print("Predicted values:") 
    print(y_pred) 
    return y_pred 

In [ ]:
# Function to calculate accuracy 
def cal_accuracy(y_test, y_pred): 
      
    print("Confusion Matrix: ", 
        confusion_matrix(y_test, y_pred)) 
      
    print ("Accuracy : ", 
    accuracy_score(y_test,y_pred)*100) 
      
    print("Report : ", 
    classification_report(y_test, y_pred)) 

In [ ]:
# Driver code 
def main(): 
      
    # Building Phase 
    data = importdata() 
    X, Y, X_train, X_test, y_train, y_test = splitdataset(data) 
    clf_gini = train_using_gini(X_train, X_test, y_train) 
    clf_entropy = tarin_using_entropy(X_train, X_test, y_train) 
      
    # Operational Phase 
    print("Results Using Gini Index:") 
      
    # Prediction using gini 
    y_pred_gini = prediction(X_test, clf_gini) 
    cal_accuracy(y_test, y_pred_gini) 
      
    print("Results Using Entropy:") 
    # Prediction using entropy 
    y_pred_entropy = prediction(X_test, clf_entropy) 
    cal_accuracy(y_test, y_pred_entropy) 

In [ ]:
# Calling main function 
if __name__=="__main__": 
    main() 

Dataset Length:  5475
Dataset Shape:  (5475, 8)
Dataset:     TotalTime  EC       AVG      Energy  Sleep  Step  HeartData  Group
0         12   2  1.500000  302.500000      8   605         58      3
1         13   3  2.166667  183.333333      4   550         58      3
2         10   1  1.428571  183.333333      7   550         57      3
3         12   2  1.500000  183.333333      5   550         66      3
4         10   1  1.250000  201.666667      4   605         79      3
Results Using Gini Index:
Predicted values:
[1. 0. 0. ... 0. 0. 0.]
Confusion Matrix:  [[1095    7    8    2]
 [   5  306    1    2]
 [ 100   25    2    9]
 [   0    3    7   71]]
Accuracy :  89.71393791844187
Report :                precision    recall  f1-score   support

         0.0       0.91      0.98      0.95      1112
         1.0       0.90      0.97      0.93       314
         2.0       0.11      0.01      0.03       136
         3.0       0.85      0.88      0.86        81

    accuracy                  