<a href="https://colab.research.google.com/github/mohammad-nahid-hossain/MSc.-Projects/blob/main/My_CI_Project_RF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
!ls "/content/drive/My Drive/"

 2014_Bodily_Maps_of_Emotions.mat
'2019110211_Hossain Mohammad Nahid.gdoc'
 Books
'Books(islamic)'
'Bsc Thesis'
 CERTIFICATES
'Colab Notebooks'
 Coursera
 CV
'Data Acquisition for research work'
 DeepLearningBook.pdf
'Dream forest tour'
'Getting started.pdf'
'GME transaction'
 Hmmmmm.gsheet
'How to install cuda 10.1 in Ubuntu 18.04.zip'
 IMG_4717.JPG
 IMG_4719.JPG
 lecture_1.pdf
 lecture_2.pdf
 lecture_3.pdf
 lecture_4.pdf
 Msc
 Neural-Network-based-finger-counting-technique.pdf
'New Doc 2019-09-03 20.05.57.jpg'
 Paper
'PhD Application'
'PhD Application Pack'
'Planning Document.docx'
'Planning Document.odt'
'Planning Document.pdf'
'Snow fall video'


In [ ]:
import numpy as np 
import pandas as pd 

In [ ]:
dataset = pd.read_csv('/content/drive/My Drive/Msc/Msc Thesis/Coding Documents/WFS/RF/My_Project_CI_data.csv') 

In [ ]:
dataset.head()

TotalTime  EC       AVG      Energy  Sleep  Step  HeartData  Group
0         12   2  1.500000  302.500000      8   605         58      3
1         13   3  2.166667  183.333333      4   550         58      3
2         10   1  1.428571  183.333333      7   550         57      3
3         12   2  1.500000  183.333333      5   550         66      3
4         10   1  1.250000  201.666667      4   605         79      3

In [ ]:
#Preparing Data For Training
X = dataset.iloc[:, 0:7].values
y = dataset.iloc[:, 7].values

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#Training the Algorihtm
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

In [ ]:
#Evaluating the Algorithm
#from sklearn import metrics

#print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
#print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
#print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

In [ ]:
#Evaluating the Algorithm 
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[765   3   1   2]
 [  4 171   0   1]
 [ 68  22   0   5]
 [  1   4   0  48]]
              precision    recall  f1-score   support

           0       0.91      0.99      0.95       771
           1       0.85      0.97      0.91       176
           2       0.00      0.00      0.00        95
           3       0.86      0.91      0.88        53

    accuracy                           0.90      1095
   macro avg       0.66      0.72      0.69      1095
weighted avg       0.82      0.90      0.86      1095

0.8986301369863013
