<a href="https://colab.research.google.com/github/mohammad-nahid-hossain/MSc.-Projects/blob/main/My_CI_Project_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
!ls "/content/drive/My Drive/"

 2014_Bodily_Maps_of_Emotions.mat
'2019110211_Hossain Mohammad Nahid.gdoc'
 Books
'Books(islamic)'
'Bsc Thesis'
 CERTIFICATES
'Colab Notebooks'
 Coursera
 CV
'Data Acquisition for research work'
 DeepLearningBook.pdf
'Dream forest tour'
'Getting started.pdf'
'GME transaction'
 Hmmmmm.gsheet
'How to install cuda 10.1 in Ubuntu 18.04.zip'
 IMG_4717.JPG
 IMG_4719.JPG
 lecture_1.pdf
 lecture_2.pdf
 lecture_3.pdf
 lecture_4.pdf
 Msc
 Neural-Network-based-finger-counting-technique.pdf
'New Doc 2019-09-03 20.05.57.jpg'
 Paper
'PhD Application'
'PhD Application Pack'
'Planning Document.docx'
'Planning Document.odt'
'Planning Document.pdf'


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
CI_data = pd.read_csv("/content/drive/My Drive/Msc/Msc Thesis/Coding Documents/SVM/My_Project_CI_data.csv")

In [ ]:
CI_data.shape

(5475, 8)

In [ ]:
CI_data.head()

TotalTime  EC       AVG      Energy  Sleep  Step  HeartData  Group
0         12   2  1.500000  302.500000      8   605         58      3
1         13   3  2.166667  183.333333      4   550         58      3
2         10   1  1.428571  183.333333      7   550         57      3
3         12   2  1.500000  183.333333      5   550         66      3
4         10   1  1.250000  201.666667      4   605         79      3

In [ ]:
X = CI_data.drop('Group', axis=1)
y = CI_data['Group']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = svclassifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score 
print(confusion_matrix(y_test,y_pred))
print ("Accuracy : ", accuracy_score(y_test,y_pred)*100) 
print(classification_report(y_test,y_pred))

[[1076   59    0    6]
 [ 153  110    0   14]
 [ 106   14    0    7]
 [   8   42    0   48]]
Accuracy :  75.1065124771759
              precision    recall  f1-score   support

           0       0.80      0.94      0.87      1141
           1       0.49      0.40      0.44       277
           2       0.00      0.00      0.00       127
           3       0.64      0.49      0.55        98

    accuracy                           0.75      1643
   macro avg       0.48      0.46      0.46      1643
weighted avg       0.68      0.75      0.71      1643



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
